name: Just Test
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Test to use variables & Secrets
      env:
        BASE_URL: ${{ env.BASE_URL }}
        SCALAR_PASSWORD: ${{ secrets.SCALAR_PASSWORD }}
      run: |
        echo "This is a test"
        echo "This is a test with a variable: $BASE_URL"
        echo "This is a test with a secret: $SCALAR_PASSWORD"
